name: automated testing
on:
  push:
    branches: [ main ]

jobs:
  automated-tests:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          node-version: [16.x]
          ci_node_total: [1]
          ci_node_index: [0]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - name: npm install and build
          run: |
            npm install

        - name: Run unit tests
          run: npm test

        # - name: Upload coverage reports to Codecov
        #   uses: codecov/codecov-action@v3
        #   env:
        #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}